version : 1.0

env:
  variables:
    AWS_ACCOUNTID: 225989340431
    REPOSITORY_NAME: "test_ci_dc"
    CONTIANER_NAME: "demo_cicd"
    CLUSTER_NAME: "test_pipeline"
    AWS_DEFAULT_REGION: "ap-south-1"
    IMAGE_TAG: "latest"

    phases:
      pre-build:
        commands:
          -echo logging into amazon ecr...
          -aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 225989340431.dkr.ecr.ap-south-1.amazonaws.com
          -REPOSITORY_URI= 225989340431.dkr.ecr.AWS_DEFAULT_REGION.amazonaws.com/REPOSITORY_NAME:IMAGE_TAG

    build:
      commands:
        -echo build started on 'date'
       -echo building docker images...
      -docker built -t $REPOSITORY_NAME:IMAGE_TAG
    -docker tag $REPOSITORY_NAME:IMAGE_TAG $REPOSITORY_URI:IMAGE_TAG

  post-build:
    commands:
      -echo build process completed successfully 
      -echo pushing the images to ecr;
      -docker push $REPOSITORY_URI:IMAGE_TAG
      -echo writing image defination file in json format...
    -printf[{"name": "%s", "imageuri": "%s"}] $CONTIANER_NAME $REPOSITORY_URI:IMAGE_TAG > imagedef.json
       artifacts:
         files: imagedef.json

